definitions:
  models.CreateExample:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    type: object
  models.Example:
    properties:
      actor_id:
        type: string
      created_at:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      updated_at:
        type: string
    type: object
  models.GetListExampleResponse:
    properties:
      count:
        type: integer
      exapmle:
        items:
          $ref: '#/definitions/models.Example'
        type: array
    type: object
  models.UpdateExample:
    properties:
      actor_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /example:
    get:
      consumes:
      - application/json
      description: Get List Example
      operationId: get_list_example
      parameters:
      - description: offset
        in: query
        name: offset
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetExampleBody
          schema:
            $ref: '#/definitions/models.GetListExampleResponse'
        "400":
          description: Invalid Argument
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Get List Example
      tags:
      - Example
    post:
      consumes:
      - application/json
      description: Create Example
      operationId: create_example
      parameters:
      - description: CreateExampleRequestBody
        in: body
        name: example
        required: true
        schema:
          $ref: '#/definitions/models.CreateExample'
      produces:
      - application/json
      responses:
        "201":
          description: GetExampleBody
          schema:
            $ref: '#/definitions/models.Example'
        "400":
          description: Invalid Argument
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Create Example
      tags:
      - Example
  /example/{id}:
    delete:
      consumes:
      - application/json
      description: Delete By Id Example
      operationId: delete_by_id_example
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetExampleBody
          schema:
            $ref: '#/definitions/models.Example'
        "400":
          description: Invalid Argument
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Delete By Id Example
      tags:
      - Example
    get:
      consumes:
      - application/json
      description: Get By Id Example
      operationId: get_by_id_example
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetExampleBody
          schema:
            $ref: '#/definitions/models.Example'
        "400":
          description: Invalid Argument
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Get By Id Example
      tags:
      - Example
    put:
      consumes:
      - application/json
      description: Update Example
      operationId: update_example
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: CreateExampleRequestBody
        in: body
        name: Example
        required: true
        schema:
          $ref: '#/definitions/models.UpdateExample'
      produces:
      - application/json
      responses:
        "200":
          description: GetExamplesBody
          schema:
            $ref: '#/definitions/models.Example'
        "400":
          description: Invalid Argument
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Update Example
      tags:
      - Example
swagger: "2.0"
